MusicApp/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions
  resources :bands do
    resources :albums, only: :new
  end

  resources :albums
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MusicApp/app/models/album.rb
class Album < ApplicationRecord

  validates :band_id, :title, :year, :studio, presence: true

  belongs_to :band,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Band

end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MusicApp/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Album
end

MusicApp/app/models/user.rb
class User < ApplicationRecord
  validates :email, :session_token, uniqueness: true

  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user && user.is_password?(password)
      return user
    else
      return nil
    end
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(pw)
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end

end

MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      @album.errors.full_messages
      render :new
  end

  def show
    @album = Album.find_by(id: params[:id])
    render :show
  end

  private

  def album_params
    params.require(:album).permit(:band_id, :title, :year, :studio)
  end
end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    current_user != nil
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end


end

MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    def new
      @band = Band.new
      render :new
    end

    def create
      @band = Band.new(band_params)
      if @band.save
        redirect_to band_url(@band)
      else
        @band.errors.full_messages
        render :new
      end

    end

    def show
      @band = Band.find_by(id: params[:id])
      render :show
    end

    private

      def band_params
        params.require(:band).permit(:name)
      end
end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end


  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = "User sign-in invalid"
      render :new
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  private
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MusicApp/app/views/albums/new.html.erb
<h1>New Album </h1>

<form action="<%=albums_url%>" method="post">
  Who Made This Album?
  <br>
  <select name="album[band_id]">
    <% bands = Bands.all %>
    <% bands.each do |band| %>
        <option value="<%=band.id%>"> <%=band.name%></option>
    <% end %>
  </select>
  <br>
  Name of Album
  <input type="text" name="album[title]">
  <br>
  Year
  <input type="text" name="album[year]">
  <br>
  <input type="submit" value="Save Band">
</form>

MusicApp/app/views/bands/new.html.erb
<h1>Add Band Profile</h1>

<form action="<%=bands_url%>" method="post">
  <input type="text" name="band[name]">
</form>

MusicApp/app/views/bands/show.html.erb
<h1> Profile of <%=@band.name%></h1>

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<% if logged_in? %>
<%      button_description = "Logout" %>
<%      url = session_url(current_user) %>
<%      status = "Logged In!" %>
<% else%>
<%      button_description = "Log In!" %>
<%      url = sessions_url %>
<%      status = "Logged Out" %>
<% end  %>
<html>
  <head>
    <link rel="stylesheet" href="styling.css">
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <h1> Welcome to the Music App</h1>

    <form action="<%=url%>" method="post">
      <% if logged_in? %>
          <input type="hidden" name="_method" value="delete">

          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input type="submit" value="<%= button_description %>">
      <%else %>
        <a href="/sessions/new"> Log In Here </a>
      <% end  %>
    </form>
      <%= yield %>
  </body>
</html>

MusicApp/app/views/users/new.html.erb
<!-- <h1>New User</h1> -->

<form action="<%=users_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  Email
  <br>
  <input type="text" name="user[email]">
  <br>
  <br>
  <br>
  Password
  <br>
  <input type="password" name="user[password]">
  <br>
  <input type="submit" value="Signup">
</form>

MusicApp/app/views/users/show.html.erb
<h1> Hi <%= @user.email %>!</h1>